name: Pre-Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Check format
        run: npm run format:check

      - name: Fix format
        run: npm run format:fix

      - name: Lint check
        run: npm run lint:check
        
      - name: Lint fix
        run: npm run lint:fix
